# Generated by Django 5.0.2 on 2024-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
